FROM alpine:latest

MAINTAINER Tatsuya Kobayashi pikopiko28@gmail.com

ENV LC_ALL C.UTF-8

RUN apk add --update \
gcc g++ make libgcrypt libgcrypt-dev openssl \
erlang erlang-dev erlang-stdlib erlang-erts erlang-tools erlang-syntax-tools \
erlang-mnesia erlang-erl-interface erlang-parsetools \
erlang-crypto erlang-eunit \
elixir nodejs mysql-client && \
mix do local.rebar --force, local.hex --force
